name: Branches on push

on:
    push:
        branches:
            - main
            - sigma

permissions:
    contents: read # for checkout

jobs:
    release:
        runs-on: ubuntu-latest

        permissions:
            contents: write # to be able to publish a GitHub release
            issues: write # to be able to comment on released issues
            pull-requests: write # to be able to comment on released pull requests
            id-token: write # to enable use of OIDC for npm provenance

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
                  registry-url: 'https://registry.npmjs.org'

            - name: Setup bun
              uses: oven-sh/setup-bun@v2

            - name: Install dependencies
              run: bun install

            - name: Build Apa-UI
              run: bun run build

            # Remove unnecessary files
            - run: rm -r .github
            - run: rm -r .husky
            - run: rm .mergify.yml
            - run: rm bun.lockb
            - run: rm commitlint.config.js
            - run: rm eslint.config.mjs
            - run: rm release.config.mjs

            - name: Semantic Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
              run: bunx semantic-release
