name: Commitlint Check

on: [push, pull_request]

jobs:
    commitlint:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Setup bun
              uses: oven-sh/setup-bun@v2

            - name: Install dependencies
              run: bun install

            - name: Validate current commit (last commit) with commitlint
              if: github.event_name == 'push'
              run: bunx commitlint --last --verbose

            - name: Validate all commits from PR
              if: github.event_name == 'pull_request'
              run: bunx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
